onflow/kitty-items

cadence/contracts/KittyItems.cdc
cadence/contracts/KittyItemsMarket.cdc
cadence/lib/go/test/kibble_test.go
cadence/lib/go/test/kitty_items_market_test.go
cadence/lib/go/test/kitty_items_test.go

Lots of projects that we are reviewing at not removing certain lines of code that were not meant to be included in production contracts, so I removed some of those.
I also added an assert in the init function of the sale offer resource that checks to see if the nft id is actually available in the collection before allowing the sale offer to be completed.
I tried to fix up the Go automated tests, but they seem to be really out of date and do not work at all. I'd love to make them work, but I don't have the bandwidth. @rheaplex @psiemens are you aware of this? We probably should try to get those working soon and set up CI on this repo.

Removes suffix and adds assert

---

.env
README.md

Closes: #81 #80 #78 
Add back .env file because of issue reported and because this way it is more obvious how to run kitty-items example

Put back env

---

cadence/lib/js/package.json
cadence/lib/js/src/kibble.js
cadence/lib/js/src/kitty-items-marketplace.js
cadence/lib/js/src/kitty-items.js
cadence/lib/js/test/kibble.test.js
cadence/lib/js/test/kitty-items-marketplace.test.js
cadence/lib/js/test/kitty-items.test.js

With updated version of `flow-js-testing` it will be possible to pass just the values of arguments, without specifying their types - which will be inferred from Cadence code.

Refactor arguments

---

web/src/hooks/use-fusd-balance.hook.js

I think the last merge of the FUSD branch broke the balance hook. 
This PR fixes this issue by using the proper function calls.

use fetchFUSDBalance instead of fetchKibblesBalance

---

api/src/services/flow.ts
web/src/flow/script.get-account-items.js
web/src/flow/tx.create-listing.js
web/src/flow/tx.initialize-account.js
web/src/flow/tx.purchase-listing.js
web/src/flow/tx.remove-listing.js
web/src/flow/util/tx.js
web/src/hooks/useMintAndList.js

FCL has been evolving and introduced various convenient wrapper functions (i.e. mutate and query). We would like to keep KittyItems code base up-to-date by following the latest FCL best practice. 
The goal of this PR is to replace all legacy fcl.send() methods with fcl.mutate and fcl.query wherever applicable 
- verified minting KittyItems work
- verified adding a listing and removing a listing works
- verified purchasing a KittyItem works
- checked both FE and BE logs to ensure there are no new errors introduced

replace legacy fcl.send() methods with latest best practice

---

.github/workflows/integration-local.yml
README.md
cadence/tests/test/kitty-items.test.js
cadence/tests/test/nft-storefront.test.js

- fix Cadence tests by importing the correct functions (which were renamed in previous commits; CI pipeline did NOT capture this because Cadence tests were disabled due to intermittent failure described in https://github.com/onflow/flow-js-testing/issues/61)
- add delays to Jest fixures to address intermittent test failures
- revive Cadence tests in Github actions
- updated README to remove outdated test contents (we no longer have Golang tests; all tests here are JS)

fix broken Cadence tests

---

api/src/services/storefront.ts

Because the file doesn't exist anymore... It should specify the new cadence file for these transactions.

Fix transaction file for buy and sell items

---

cadence/tests/package.json
cadence/tests/src/common.js
cadence/tests/src/kitty-items.js
cadence/tests/src/nft-storefront.js

Starting 0.2.0, flow-js-testing library introduced a breaking change in terms of exception handling -- instead of raising the error encountered when running script/transaction, the library will return the error along with the data (Golang style). This requires code update on tests to raise the error if the error is not nil. 
This change introduced three wrappers which will perform the check and raise the error if it's present

upgrade flow-js-testing library

---

cadence/tests/package.json

Pilot usage of 0.2.2 (introduced in PR https://github.com/onflow/flow-js-testing/pull/73) of flow-js-testing library which makes request to getBlock() API to determine readiness of the Flow emulator (instead of relying on logging lines)
We can upgrade to a stable version (i.e 0.2.2) when the alpha version is vetted by the community.

use flow-js-testing lib 0.2.2

---

api/Dockerfile.dev

I was getting `tsnd: not found` errors in the api container. Adding npm i to the Dockerfile fixed it. Another similar error report: https://forum.onflow.org/t/getting-started-with-kitty-item-demo-project/2324/2
- Successfully started the api container

Run npm install in api Dockerfile

---

cadence/transactions/flow/mint_tokens.cdc

The return type of FlowToken's mintTokens was `FlowToken.Vault`.
However, deposit function input parameter is `FungibleToken.Vault`. I thought this was meant to be, so I edited it.

Add missing allowedAmount parameter

---

web/src/util/events.js

#190 split the storefront address from the flow address to support testnet deploys. This updates the address used to query for events.
- NFTStorefront.ListingAvailable was found on testnet

Update storefront event address

---

web/src/components/ProfileAccountItems.jsx

useApiListings was using the wrong param format
- Profile account items were successfully loaded on testnet

Fix useApiListings param argument on ProfileAccountItems

---

cadence/contracts/KittyItems.cdc
cadence/contracts/NFTStorefront.cdc
cadence/tests/package-lock.json
cadence/transactions/kittyItems/setup_account.cdc

**Summary**
This repo is something is great for learning! It should implement the changes required for `Secure Cadence` and the NFT Standard so more people will implement their NFTs correctly.
I installed the Secure Cadence version of Flow and updated the contract to adhere to it. 
**Test Plan**
Ran the JS test suite and confirmed everything passes. Please let me know if I missed anything.
> NOTE: The build doesn't use the most up to date flow version. I can change this too but left it out for now.

Change KittyItems to support secure cadence and implement Metadata standard

---

cadence/contracts/KittyItems.cdc
cadence/contracts/MetadataViews.cdc

**Summary**
More metadata views have been introduced since this NFT was last updated. Adding the collection level views as well as the external url view. Similarly implemented [here](https://github.com/onflow/flow-nft/blob/master/contracts/ExampleNFT.cdc)
**Test Plan**
Ran the JS test suite and confirmed everything passes. Please let me know if I missed anything.

Implement collection and external url standard metadata views

---

cadence/tests/package-lock.json
cadence/tests/package.json
cadence/tests/src/common.js
cadence/tests/src/kitty-items.js
cadence/tests/src/nft-storefront.js
cadence/tests/test/kitty-items.test.js
cadence/tests/test/nft-storefront.test.js

1. flow-js-testing has been migrated to the @onflow organization (@onflow/flow-js-testing)
2. 0.3.0 introduces dynamic port selection for the emulator and removes the statically supplied ports

Update @onflow/flow-js-testing to 0.3.0-alpha.8

---

.github/workflows/integration-local.yml
.ki-scripts/startup.js
cypress.config.js
cypress/e2e/emulator.cy.js
cypress/e2e/testnet.cy.js
web/pages/admin/mint.jsx
web/pages/index.jsx
web/pages/marketplace.jsx
web/pages/profiles/[address].jsx
web/pages/profiles/[address]/items/[id].jsx
web/src/components/Avatar.jsx
web/src/components/Header.jsx
web/src/components/HeaderDropdown.jsx
web/src/components/HeaderFLOWBalance.jsx
web/src/components/HomeEmptyMessage.jsx
web/src/components/LatestStoreItems.jsx
web/src/components/Minter.jsx
web/src/components/RarityScale.jsx
web/src/components/SellListItem.jsx
web/src/components/TransactionLoading.jsx

Scenarios that do not interact with kitty items:
* Visits header buttons
* Logs in as admin
* Creates new account
Scenarios that involve minting kitty items:
* Mints an item as from a service account + remove from store
* Mints an item + funds an account + purchases item from the funded account
* Log in and out from user accounts handled in 'beforeEach' and 'afterEach'
Accounts
KI
Scenarios that do not require calling external apps:
* Visits header buttons
* Logs in as admin + mint an item
* Connects to Blocto wallet with testnet account 
Next Issue: https://github.com/onflow/kitty-items/issues/289
- Cover Testnet scenarios that need external services (Issue: https://github.com/onflow/kitty-items/issues/289)
- Configure github actions to run both Emulator & Testnet tests in separate …

Add cypress e2e tests for emulator

---

.github/workflows/integration-local.yml

Updating conditions to run e2e tests. The tests should run when the master branch is updated.

Run e2e tests on master push

---

.ki-scripts/startup.js

Issue: https://github.com/onflow/kitty-items/issues/300
Bug Cause: This bug was caused by my refactoring in the startup.js testnet setup. The check for the env setup (for testnet, this means checking that the testnet config files exist) was happening before the account creation dialogue, which results in startup failure (since most new users would not have this file pre-configured). This startup path is also the only path not tested during cypress e2e testing - this is because the cypress e2e tests use an existing testnet account and does not require the testnet configuration file for startup. See diff here: https://github.com/onflow/kitty-items/pull/295/files#diff-b6fd80401f711ce5defc777da468bde51d75d7dd5759f2c02769fe19d8d54dbf
Fix: Moving the environment check to the end of the block, …

Bug Fix - Move the check for env config to after account setup 

---

README.md

Updated "Testnet development" section to add a warning about updated storage paths. It prompts the user to create a new Blocto account.

Update README to warn about updated storage paths
