onflow/kitty-items

- api/package-lock.json
- api/package.json
- api/src/config.ts
- api/src/services/flow.ts
- api/src/workers/base-event-handler.ts
- web/package-lock.json
- web/package.json
- Removes `sdk` imports in favour of `fcl`
- Updates authz to correctly parse address (Fixes https://github.com/onflow.flow-js-sdk/issues/639)
- Updates `fcl` to latest version
> Removes sdk, updates authz.

- cadence/lib/js/src/kibble.js
- cadence/lib/js/src/kitty-items-marketplace.js
- cadence/lib/js/src/kitty-items.js
- cadence/lib/js/test/kitty-items-marketplace.test.js
- cadence/lib/js/test/kitty-items.test.js
Remove explicit addressMaps passed to interaction
> Simplify code

- cadence/lib/js/package-lock.json
- cadence/lib/js/package.json
- cadence/lib/js/src/kitty-items-marketplace.js
- cadence/lib/js/src/kitty-items.js
- cadence/lib/js/test/kibble.test.js
- cadence/lib/js/test/kitty-items-marketplace.test.js
- cadence/lib/js/test/kitty-items.test.js
Closes https://github.com/onflow/flow-js-testing/issues/37
- update file names
- update Jest version
- update before and after hooks
> Fix Javascript Test

- api/package-lock.json
0eaf6b7 introduced malformed JSON
> Fix malformed JSON in api/package-lock.json

- .env.testnet
> use local name to resolve database and provide correct api backend

- cadence/tests/js/flow.json
- cadence/tests/js/package-lock.json
- cadence/tests/js/package.json
- cadence/tests/js/test/kibble.test.js
- cadence/tests/js/test/kitty-items.test.js
- cadence/tests/js/test/nft-storefront.test.js
- Update test dependencies
- Refactor use of "init" method
> Minor refactoring updates

- README.md
I am a new developer to this project and do not realize initializing that service account is a must-have, and spent over one hour trying to debug the error below (which is as a result of not initializing the service account):
Hence updating the README to explicitly call out the necessity to initialize the service account for the very first time
> update README to mention initialization of Service Account

- web/src/hooks/useListings.js
- verified profile listings are showing correctly
> Fix expandListingsKey typo

- web/package-lock.json
- web/package.json
- web/pages/marketplace.jsx
Fixes hydration errors by moving router calls to a useEffect() and updates nextjs. This should resolve #187
- Opened the marketplace page, and saw no console errors
> Move router.isReady call to useEffect()

- web/src/components/Minter.jsx
- web/src/components/MinterLoader.jsx
> Move MinterLoader to separate component, decouple from ListItemImage

- api/src/services/kitty-items.ts
- web/src/global/constants.js
https://github.com/onflow/kitty-items/issues/180
> Update rarity percentages

- web/pages/profiles/[address]/items/[id].jsx
- web/src/components/LatestMarketplaceItems.jsx
- web/src/components/LatestStoreItems.jsx
- web/src/components/ListItem.jsx
- web/src/components/ListItemImage.jsx
- web/src/components/Minter.jsx
- web/src/components/MinterLoader.jsx
- web/styles/globals.css
- Always show buy button
- Add border on hover
- Set ListItem image aspect ratio to prevent content reflow
- Misc lint fixes
https://github.com/onflow/kitty-items/issues/181
> ListItem style updates

- web/pages/index.jsx
- web/pages/marketplace.jsx
- web/pages/profiles/[address]/items/[id].jsx
- web/src/components/HeaderMessage.jsx
- web/src/components/LatestMarketplaceItems.jsx
- web/src/components/LatestStoreItems.jsx
- web/src/components/ListItem.jsx
- web/src/components/ListItemImage.jsx
- web/src/components/ListItemPageButtons.jsx
- web/src/components/ListItems.jsx
- web/src/components/MarketplaceFilters.jsx
- web/src/components/Minter.jsx
- web/src/components/MinterLoader.jsx
- web/src/components/Pagination.jsx
- web/styles/globals.css
- web/tailwind.config.js
- Add "new" tag to latest items and update button sizes
- Move latest titles + control buttons above carousel
- Add Marketplace Listings subheader
- Update header message styling
https://github.com/onflow/kitty-items/issues/182
> Update homepage styling

- web/pages/marketplace.jsx
- web/pages/profiles/[address]/items/[id].jsx
- web/src/components/LatestMarketplaceItems.jsx
- web/src/components/LatestStoreItems.jsx
- web/src/components/ListItem.jsx
- web/src/components/ListItemImage.jsx
- web/src/components/ListItems.jsx
- web/src/components/MarketplaceFilters.jsx
- web/src/components/Minter.jsx
- web/src/components/MinterLoader.jsx
- web/src/components/Pagination.jsx
- web/styles/globals.css
- Add pagination to top of marketplace page
- Hide top pagination on mobile
https://github.com/onflow/kitty-items/issues/183
> Add pagination to top of marketplace page

- api/src/services/storefront.ts
- web/pages/marketplace.jsx
- web/pages/profiles/[address].jsx
- web/pages/profiles/[address]/items/[id].jsx
- web/src/components/Avatar.jsx
- web/src/components/LatestMarketplaceItems.jsx
- web/src/components/LatestStoreItems.jsx
- web/src/components/ListItemImage.jsx
- web/src/components/ListItems.jsx
- web/src/components/ProfileAccountItems.jsx
- web/src/components/ProfileListings.jsx
- web/src/hooks/useAccountItem.js
- web/src/hooks/useAccountItems.js
- web/src/hooks/useApiListings.js
- web/src/hooks/useFLOWBalance.js
- web/src/hooks/useListing.js
- web/src/hooks/useListings.js
- web/src/util/currency.js
Continuation of #190
- Profile and item pages are loading successfully on testnet
> Pre-render item and profile pages before data is loaded

- .env.testnet
- flow.testnet.json
- Add MetadataViews contract to testnet deployments: fixes #211
- Update testnet DB_URL to working url
> Add MetadataViews contract to testnet deployments, update DB_URL

- api/src/services/storefront.ts
- cadence/scripts/nftStorefront/get_listing_item.cdc
- web/cadence/scripts/get_account_item.cdc
- web/cadence/scripts/get_listing.cdc
- web/src/components/Header.jsx
- web/src/util/normalize-item.js
Related conversation: https://github.com/onflow/kitty-items/pull/221#discussion_r822925970
> Convert KittyItem kind/rarity ints to enums

- api/src/services/kitty-items.ts
- cadence/contracts/KittyItems.cdc
- cadence/tests/src/kitty-items.js
- web/src/global/constants.js
> feat: remove nft kind for shades

- api/src/migrations/20201214150404_create_block_cursor.ts
- api/src/models/block-cursor.ts
- api/src/routes/kitty-items.ts
- api/src/routes/storefront.ts
- api/src/services/block-cursor.ts
- api/src/services/storefront.ts
- api/src/workers/base-event-handler.ts
- api/src/workers/listing-handler.ts
- cadence/contracts/KittyItems.cdc
- cadence/transactions/kittyItems/mint_and_list_kitty_item.cdc
- cadence/transactions/nftStorefront/create_listing.cdc
- package-lock.json
- package.json
- web/cadence/transactions/create_listing.cdc
- web/package-lock.json
- web/package.json
- fixed issue where ListingAvailable event was fetching a listing that was already completed
- added some documentation for api classes
- dependency updates
> bug: unable to list newly purchased kittyitem

- .ki-scripts/startup.js
Related with issue [Unknown file extension ".CMD" #241](https://github.com/onflow/kitty-items/issues/241#issuecomment-1144726795)
> Resolve pm2 problem in Windows

- api/package.json
- api/src/workers/base-event-handler.ts
- package.json
- web/src/components/Header.jsx
- Added 200 block range limit for event handler query
- updated api package.json's node version requirement
- Fixed header typo
> small kitty items update

- package.json
> Add stop script

- .github/workflows/integration-local.yml
- .ki-scripts/startup.js
- Updated run command for the project in workflow 
- Updated node version 14.x -> 16.x
- Removed obsolete steps in workflow related to docker-compose and cypress
> Fixed github actions CI script

- api/package-lock.json
- api/src/services/flow.ts
- api/src/services/storefront.ts
- refactored `getListingItem()` to execute script on specific blockId
> listing event edge case fix

- cadence/contracts/FungibleToken.cdc
- cadence/contracts/KittyItems.cdc
- cadence/contracts/MetadataViews.cdc
- cadence/contracts/NFTCatalog.cdc
- cadence/tests/src/kitty-items.js
- cadence/transactions/kittyItems/mint_and_list_kitty_item.cdc
- cadence/transactions/kittyItems/mint_kitty_item.cdc
- cadence/transactions/nftStorefront/purchase_listing.cdc
- web/cadence/transactions/purchase_listing.cdc
* Updated metadata contract to the most recent version according to storefront
* Updated other contracts and transactions to recent changes
> Update Metadata Contract for NFT Catalog
